services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zodiac-backend
    command: uvicorn api_server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app   # remove this in production

  frontend:
    build:
      context: ./frontend/my-react-app
      dockerfile: Dockerfile
    container_name: zodiac-frontend
    ports:
      - "5173:80"   # external:internal
    environment:
      - VITE_API_BASE_URL=/api
    depends_on:
      - backend
